services:

  db:
    image: postgres:17.5
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    build:
      context: .
    container_name: backend
    restart: always
    working_dir: /server
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app/:/server
      - ./static:/server/static
    command: >
      sh -c "cd /server &&
      alembic upgrade head &&
      gunicorn main:create_application --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

  telegram-bot:
    build:
      context: .
    container_name: telegram-bot
    restart: always
    working_dir: /server
    ports:
      - "8001:8001"
    depends_on:
      - db
      - backend
    env_file:
      - .env
    volumes:
      - ./app/:/server
    command: >
      sh -c "cd /server &&
      gunicorn telegram_bot_main:create_application --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001"

volumes:
  db-volume:

